const activities = [
  "combining all the leftover cake slices into a single, monstrous cake",
  "reprogramming the vacuum cleaner to have deep philosophical conversations",
  "convincing the garden gnomes to unionize for better working conditions",
  "training the pet llama to juggle flaming swords",
  "accidentally summoning a swarm of bees instead of decorating the kitchen",
  "enrolling the grim reaper in a knitting class",
  "convincing the furniture that it's actually part of an obstacle course",
  "blaming a plumbing disaster on the neighborhood ghosts",
  "installing teleporters in places that will definitely confuse the postman",
  "teaching the plants to gossip about the neighbors",
  "trying to figure out why the house smells like burnt lasagna and existential dread",
  "writing love letters to the kitchen appliances just to see what happens",
  "encouraging the local raccoon to start a tech startup",
  "inventing new types of bugs so the exterminator has something to do",
  "spontaneously combusting the refrigerator for comedic effect",
  "installing a trampoline in the middle of the bathroom",
  "gluing everyone's shoes to the ceiling as an avant-garde art installation",
  "discovering that the dishwasher is plotting world domination",
  "hiring a mime to do interpretive dance in the living room",
  "baking a loaf of bread shaped like a t-rex because science demands it",
  "teaching the fish to play chess, but they keep cheating",
  "building a secret room filled with nothing but rubber ducks",
  "hosting an underwater tea party with invisible guests",
  "growing a giant potato in the backyard",
  "staging a surprise opera performance in the bathroom",
  "training the raccoon to moonlight as a private detective",
  "translating the dog's barking into a critically-acclaimed novel",
  "arguing with the shower about proper water temperature",
  "reprogramming the microwave to write poetry instead of heating food",
  "installing a portal to another dimension under the couch cushions",
  "hosting a reality TV show starring the houseplants",
  "hiring a butler who only communicates in riddles",
  "replacing all the furniture with jelly sculptures and hoping no one notices",
  "creating a family of sentient sandwiches to help with household chores",
  "debugging the coffee maker's sudden desire to join the cloud",
  "asking the AI assistant to tell you a joke and accidentally causing a system crash",
  "rebooting the router because it has too many existential questions",
  "uploading the blender's consciousness to the blockchain",
  "attempting to use the microwave as a WiFi extender",
  "teaching the dishwasher to write Python scripts in its spare time",
  "modding the doorbell to play the Windows startup sound",
  "trying to explain quantum computing to the toaster",
  "installing a firewall in the fridge to stop the cheese from accessing the internet",
  "teaching the TV to solve CAPTCHAs",
  "building a perpetual motion machine powered by chocolate milk and hope",
  "accidentally inventing teleportation while trying to microwave soup",
  "proving that chickens can learn advanced calculus with enough motivation",
  "attempting to send text messages to the past with a microwave and bananas",
  "testing if a microwave can open wormholes when set to defrost",
  "running experiments to control the weather using a hairdryer and two paperclips",
  "turning the microwave into a particle accelerator",
  "using magnets and bananas to alter causality, but only ending up with really weird phone calls",
];

export function getRandomActivity(): string {
  return activities[Math.floor(Math.random() * activities.length)];
}
